"""Account-agnostic distribution for finished daily-news episodes.

The browser session is the credential boundary: channel IDs and handles are
discovered at publish time and written to an immutable-per-attempt manifest.
No account identifier is accepted from task configuration or stored in code.
"""

from __future__ import annotations

import asyncio
import hashlib
import json
import logging
import re
import time
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from datetime import datetime, timezone
from email.utils import format_datetime
from pathlib import Path
from typing import Any
from urllib.parse import quote

from backend import config, database
from backend.models import TaskResponse
from backend.pipeline.opencli import OpenCLIError, first_json, run_opencli_with_retries

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class PublicationResult:
    action: str
    reason: str
    publication_url: str | None = None


def _task_dir(task: TaskResponse) -> Path:
    return Path(task.output_dir) if task.output_dir else config.OUTPUTS_DIR / task.id


def _publication_dir(task: TaskResponse) -> Path:
    path = _task_dir(task) / "publications"
    path.mkdir(parents=True, exist_ok=True)
    return path


def _manifest_path(task: TaskResponse) -> Path:
    return _publication_dir(task) / "manifest.json"


def read_publication_manifest(task: TaskResponse) -> dict[str, Any]:
    path = _manifest_path(task)
    if not path.is_file():
        return {"task_id": task.id, "platforms": {}}
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
        return value if isinstance(value, dict) else {"task_id": task.id, "platforms": {}}
    except (OSError, json.JSONDecodeError):
        return {"task_id": task.id, "platforms": {}}


def _write_manifest(task: TaskResponse, manifest: dict[str, Any]) -> None:
    path = _manifest_path(task)
    manifest["task_id"] = task.id
    manifest["updated_at"] = datetime.now(timezone.utc).isoformat()
    temporary = path.with_suffix(".tmp")
    temporary.write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")
    temporary.replace(path)


def _record(task: TaskResponse, platform: str, payload: dict[str, Any]) -> dict[str, Any]:
    manifest = read_publication_manifest(task)
    manifest.setdefault("platforms", {})[platform] = payload
    _write_manifest(task, manifest)
    return manifest


def _title(task: TaskResponse) -> str:
    return task.generated_title or task.source_title or f"Frontier Tech Daily — {task.origin_id or task.id}"


def _description(task: TaskResponse, marker: str | None = None) -> str:
    dossier = _task_dir(task) / "research" / "dossier.json"
    sources: list[str] = []
    if dossier.is_file():
        try:
            data = json.loads(dossier.read_text(encoding="utf-8"))
            # Current research dossiers store the final shortlist under
            # ``selected``.  Keep ``stories`` as a compatibility fallback for
            # already-generated episodes from the earlier schema.
            selected = data.get("selected")
            if not isinstance(selected, list):
                selected = data.get("stories", [])
            sources = [
                str(item.get("url"))
                for item in selected
                if isinstance(item, dict) and item.get("url")
            ]
        except (OSError, json.JSONDecodeError):
            pass
    lines = [
        "A source-linked daily briefing on AI and frontier technology.",
        "Generated by FrontierTechSN; factual claims received an independent ChatGPT review.",
    ]
    if marker:
        lines.append(f"Test run: {marker}")
    if sources:
        lines.extend(["", "Sources:", *sources[:10]])
    return "\n".join(lines)[:4900]


async def _browser(
    session: str,
    *args: str,
    timeout: int = 180,
    attempts: int | None = None,
    window: str | None = None,
) -> str:
    # YouTube Studio repeatedly stalls when Chrome leaves its upload/edit tab
    # in the background.  Keep those sessions foregrounded; X's dedicated
    # adapter remains safe and faster in the background.
    effective_window = window or (
        "foreground" if session.startswith("ftsn-yt-") else "background"
    )
    result = await run_opencli_with_retries(
        ["browser", session, *args, "--window", effective_window],
        timeout=timeout,
        attempts=attempts,
        label=f"OpenCLI browser {session}",
    )
    return result.stdout


_CHROME_UPLOAD_PERMISSION_HELP = (
    "Chrome blocked local file upload. Open chrome://extensions, click Details "
    "under the ChatGPT browser extension, enable 'Allow access to file URLs', "
    "then retry the publication."
)


async def _upload_local_media(
    session: str,
    *upload_args: str,
    timeout: int,
) -> str:
    """Upload once to detect a permanent Chrome permission failure quickly.

    Transient bridge failures still receive the project's full ten-attempt
    budget. Chrome's explicit ``Not allowed`` response is configuration-bound,
    so retrying it ten times only hides the actionable prerequisite.
    """
    try:
        return await _browser(
            session,
            "upload",
            *upload_args,
            timeout=timeout,
            attempts=1,
        )
    except OpenCLIError as exc:
        if "not allowed" in str(exc).casefold():
            raise OpenCLIError(_CHROME_UPLOAD_PERMISSION_HELP) from exc
    remaining_attempts = max(1, config.OPENCLI_MAX_ATTEMPTS - 1)
    return await _browser(
        session,
        "upload",
        *upload_args,
        timeout=timeout,
        attempts=remaining_attempts,
    )


async def _browser_json(session: str, *args: str, timeout: int = 180) -> Any:
    output = await _browser(session, *args, timeout=timeout)
    try:
        # ``browser eval`` legitimately emits JSON primitives such as ``true``
        # for wait predicates, not only objects and arrays.
        return json.loads(output)
    except json.JSONDecodeError:
        # Preserve compatibility with OpenCLI commands that prefix a JSON
        # object/array with human-readable status text.
        return first_json(output)


async def _wait_for(
    session: str,
    javascript: str,
    *,
    timeout_seconds: int,
    interval_seconds: float = 3.0,
) -> Any:
    deadline = time.monotonic() + timeout_seconds
    last: Any = None
    while time.monotonic() < deadline:
        last = await _browser_json(session, "eval", javascript, timeout=60)
        if last:
            return last
        await asyncio.sleep(interval_seconds)
    raise OpenCLIError(f"Browser condition did not become true within {timeout_seconds}s: {last!r}")


async def _x_identity() -> dict[str, Any]:
    result = await run_opencli_with_retries(
        [
            "twitter", "whoami", "--window", "background", "--site-session", "ephemeral",
            "--keep-tab", "false", "-f", "json",
        ],
        timeout=90,
        label="X account identity",
    )
    value = first_json(result.stdout)
    rows = value if isinstance(value, list) else [value]
    identity = rows[0] if rows and isinstance(rows[0], dict) else {}
    handle = str(identity.get("username") or "").lstrip("@")
    if not handle:
        raise OpenCLIError("X is not logged in or its current handle could not be identified")
    return identity


async def publish_x(task: TaskResponse, *, test_mode: bool) -> dict[str, Any]:
    if not task.video_path or not Path(task.video_path).is_file():
        raise FileNotFoundError("Final video is missing")
    identity = await _x_identity()
    handle = str(identity["username"]).lstrip("@")
    marker = f"FTSN-{task.id[:8]}"
    text = (
        f"{_title(task)}\n\n"
        "Today’s source-linked briefing on AI and frontier technology. "
        f"{marker}"
    )[:270]
    session = f"ftsn-x-{task.id[:8]}"
    try:
        await _browser(session, "open", "https://x.com/compose/post", timeout=90)
        await _upload_local_media(
            session, "--testid", "fileInput", "--nth", "0",
            str(Path(task.video_path).resolve()), timeout=300,
        )
        await _browser(
            session, "fill", "--testid", "tweetTextarea_0", "--nth", "0", text,
            timeout=90,
        )
        await _wait_for(
            session,
            "(()=>{const b=[...document.querySelectorAll('[data-testid=tweetButton]')].find(x=>x.offsetParent&&!x.disabled&&x.getAttribute('aria-disabled')!=='true');return b?true:false})()",
            timeout_seconds=600,
            interval_seconds=5,
        )
        await _browser(session, "click", "--testid", "tweetButton", "--nth", "0", timeout=180)
    finally:
        try:
            await _browser(session, "close", timeout=30)
        except Exception:
            logger.warning("Could not close X browser session %s", session)

    search = await run_opencli_with_retries(
        [
            "twitter", "search", f'"{marker}"', "--from", handle, "--product", "live",
            "--limit", "5", "--window", "background", "--site-session", "ephemeral",
            "--keep-tab", "false", "-f", "json",
        ],
        timeout=120,
        label="X publication verification",
    )
    value = first_json(search.stdout)
    rows = value if isinstance(value, list) else [value]
    row = next(
        (item for item in rows if isinstance(item, dict) and marker in str(item.get("text") or "")),
        None,
    )
    if not row or not row.get("url"):
        raise OpenCLIError("X composer completed but the exact test marker was not found on the current account")
    url = str(row["url"])
    if not re.match(rf"https://(?:x\.com|twitter\.com)/{re.escape(handle)}/status/\d+", url, re.I):
        raise OpenCLIError(f"X returned a post owned by an unexpected account: {url}")
    return _record(task, "x", {
        "status": "published",
        "published_at": datetime.now(timezone.utc).isoformat(),
        "identity": {"username": handle, "display_name": identity.get("name")},
        "url": url,
        "external_id": row.get("id"),
        "marker": marker,
        "test_mode": test_mode,
        "sha256": hashlib.sha256(Path(task.video_path).read_bytes()).hexdigest(),
    })["platforms"]["x"]


async def delete_x(task: TaskResponse) -> dict[str, Any]:
    entry = read_publication_manifest(task).get("platforms", {}).get("x") or {}
    url = str(entry.get("url") or "")
    if entry.get("status") != "published" or not re.fullmatch(
        r"https://(?:x\.com|twitter\.com)/[^/]+/status/\d+", url
    ):
        raise OpenCLIError("Refusing to delete X content without an exact recorded publication URL")
    identity = await _x_identity()
    current = str(identity.get("username") or "").lstrip("@")
    expected = str(entry.get("identity", {}).get("username") or "").lstrip("@")
    if current.casefold() != expected.casefold():
        raise OpenCLIError(f"Refusing X deletion: published as @{expected}, currently signed in as @{current}")
    await run_opencli_with_retries(
        ["twitter", "delete", url, "--window", "background", "--site-session", "ephemeral", "--keep-tab", "false", "-f", "json"],
        timeout=120,
        label="X exact-post deletion",
    )
    entry.update({"status": "deleted", "deleted_at": datetime.now(timezone.utc).isoformat()})
    return _record(task, "x", entry)["platforms"]["x"]


async def _youtube_identity(session: str) -> dict[str, str]:
    await _browser(session, "open", "https://studio.youtube.com/", timeout=120)
    value = await _wait_for(
        session,
        "(()=>{const m=location.href.match(/\\/channel\\/([^/]+)/);const n=document.querySelector('#channel-name')?.textContent?.trim()||document.querySelector('ytcp-navigation-drawer #entity-name')?.textContent?.trim()||'';return m?{channel_id:m[1],channel_name:n,url:location.href}:null})()",
        timeout_seconds=120,
    )
    if not isinstance(value, dict) or not value.get("channel_id"):
        raise OpenCLIError("YouTube Studio did not expose a logged-in channel")
    return {key: str(value.get(key) or "") for key in ("channel_id", "channel_name", "url")}


async def publish_youtube(task: TaskResponse, *, visibility: str, test_mode: bool) -> dict[str, Any]:
    if not task.video_path or not Path(task.video_path).is_file():
        raise FileNotFoundError("Final video is missing")
    visibility = visibility if visibility in {"private", "unlisted", "public"} else "private"
    # A fresh lease per invocation prevents a previously timed-out Studio tab
    # from poisoning a later retry of the same task.
    session = f"ftsn-yt-{task.id[:8]}-{time.time_ns()}"
    marker = f"FTSN-{task.id[:8]}"
    title = f"{_title(task)}{' [TEST]' if test_mode else ''}"[:95]
    link: Any = ""
    identity: dict[str, str] = {}
    try:
        identity = await _youtube_identity(session)
        upload_url = f"https://studio.youtube.com/channel/{quote(identity['channel_id'])}/videos/upload?d=ud"
        await _browser(session, "open", upload_url, timeout=120)
        await _upload_local_media(
            session, "input[name=Filedata]", str(Path(task.video_path).resolve()),
            timeout=300,
        )
        await _wait_for(
            session,
            "(()=>document.querySelector('#title-textarea #textbox')?true:false)()",
            timeout_seconds=300,
            interval_seconds=5,
        )
        await _browser(session, "fill", "#title-textarea #textbox", title, timeout=90)
        await _browser(session, "fill", "#description-textarea #textbox", _description(task, marker), timeout=90)
        try:
            await _browser(session, "click", "--name", "No, it's not made for kids", "--role", "radio", timeout=60)
        except Exception:
            await _browser_json(session, "eval", "(()=>{const r=[...document.querySelectorAll('tp-yt-paper-radio-button')].find(x=>/not made for kids/i.test(x.textContent||''));if(r){r.click();return true}return false})()")
        for _ in range(3):
            await _wait_for(
                session,
                "(()=>{const b=document.querySelector('#next-button');return b&&!b.disabled?true:false})()",
                timeout_seconds=600,
                interval_seconds=5,
            )
            await _browser(session, "click", "#next-button", timeout=90)
        labels = {"private": "Private", "unlisted": "Unlisted", "public": "Public"}
        await _browser(session, "click", "--name", labels[visibility], "--role", "radio", timeout=90)
        await _wait_for(
            session,
            "(()=>{const b=document.querySelector('#done-button');return b&&!b.disabled?true:false})()",
            timeout_seconds=1800,
            interval_seconds=8,
        )
        link = await _browser_json(
            session,
            "eval",
            "(()=>document.querySelector('a[href*=\"youtu.be/\"]')?.href||document.querySelector('a[href*=\"watch?v=\"]')?.href||'')()",
            timeout=60,
        )
        await _browser(session, "click", "#done-button", timeout=180)
        if not link:
            link = await _wait_for(
                session,
                "(()=>{const a=[...document.querySelectorAll('a')].find(x=>/youtu\\.be\\/|watch\\?v=/.test(x.href||''));return a?a.href:''})()",
                timeout_seconds=120,
            )
    finally:
        try:
            await _browser(session, "close", timeout=30)
        except Exception:
            logger.warning("Could not close YouTube browser session %s", session)
    link = str(link)
    match = re.search(r"(?:youtu\.be/|[?&]v=)([A-Za-z0-9_-]{6,})", link)
    if not match:
        raise OpenCLIError(f"YouTube upload completed without a canonical video ID: {link!r}")
    video_id = match.group(1)
    return _record(task, "youtube", {
        "status": "published",
        "published_at": datetime.now(timezone.utc).isoformat(),
        "identity": identity,
        "url": f"https://youtu.be/{video_id}",
        "external_id": video_id,
        "visibility": visibility,
        "marker": marker,
        "test_mode": test_mode,
        "sha256": hashlib.sha256(Path(task.video_path).read_bytes()).hexdigest(),
    })["platforms"]["youtube"]


async def delete_youtube(task: TaskResponse) -> dict[str, Any]:
    entry = read_publication_manifest(task).get("platforms", {}).get("youtube") or {}
    video_id = str(entry.get("external_id") or "")
    channel_id = str(entry.get("identity", {}).get("channel_id") or "")
    if entry.get("status") != "published" or not re.fullmatch(r"[A-Za-z0-9_-]{6,}", video_id):
        raise OpenCLIError("Refusing to delete YouTube content without an exact recorded video ID")
    session = f"ftsn-yt-delete-{task.id[:8]}-{time.time_ns()}"
    try:
        identity = await _youtube_identity(session)
        if identity["channel_id"] != channel_id:
            raise OpenCLIError("Refusing YouTube deletion because the active channel changed")
        await _browser(session, "open", f"https://studio.youtube.com/video/{video_id}/edit", timeout=120)
        current_title = await _wait_for(
            session,
            "(()=>document.querySelector('#title-textarea #textbox')?.textContent?.trim()||'')()",
            timeout_seconds=180,
        )
        await _wait_for(
            session,
            "(()=>{const b=document.querySelector('#overflow-menu-button')||document.querySelector('#more-options-button')||document.querySelector('[aria-label*=\"More options\"]');return b?true:false})()",
            timeout_seconds=180,
        )
        try:
            await _browser(session, "click", "#overflow-menu-button", timeout=60)
        except Exception:
            try:
                await _browser(session, "click", "#more-options-button", timeout=60)
            except Exception:
                await _browser(session, "click", "--name", "More options", "--role", "button", timeout=60)
        try:
            await _browser(
                session,
                "click",
                "--name",
                "Delete",
                "--role",
                "menuitem",
                timeout=60,
            )
        except Exception:
            await _browser(session, "click", "--text", "Delete forever", timeout=60)
        await _wait_for(
            session,
            "(()=>document.querySelector('ytcp-video-delete-dialog #confirm-checkbox,ytcp-video-delete-dialog input[type=checkbox]')?true:false)()",
            timeout_seconds=90,
        )
        confirm_input = await _browser_json(
            session,
            "eval",
            "(()=>document.querySelector('ytcp-video-delete-dialog #confirm-input textarea')?true:false)()",
        )
        if confirm_input:
            await _browser(
                session,
                "fill",
                "ytcp-video-delete-dialog #confirm-input textarea",
                str(current_title),
                timeout=60,
            )
        await _browser_json(
            session,
            "eval",
            "(()=>{const c=document.querySelector('ytcp-video-delete-dialog #confirm-checkbox #checkbox')||document.querySelector('ytcp-video-delete-dialog [role=checkbox]')||document.querySelector('ytcp-video-delete-dialog input[type=checkbox]');if(c){if(c.getAttribute('aria-checked')!=='true'&&!c.checked)c.click();return true}return false})()",
        )
        await _wait_for(
            session,
            "(()=>{const b=document.querySelector('ytcp-video-delete-dialog #confirm-button')||[...document.querySelectorAll('ytcp-video-delete-dialog ytcp-button,ytcp-video-delete-dialog button')].find(x=>/delete forever/i.test(x.textContent||''));return b&&b.getAttribute('aria-disabled')!=='true'&&!b.disabled?true:false})()",
            timeout_seconds=90,
        )
        await _browser_json(
            session,
            "eval",
            "(()=>{const b=document.querySelector('ytcp-video-delete-dialog #confirm-button')||[...document.querySelectorAll('ytcp-video-delete-dialog ytcp-button,ytcp-video-delete-dialog button')].find(x=>/delete forever/i.test(x.textContent||''));if(b&&b.getAttribute('aria-disabled')!=='true'&&!b.disabled){b.click();return true}return false})()",
        )
        await _wait_for(
            session,
            f"(()=>!location.href.includes('/video/{video_id}/edit'))()",
            timeout_seconds=180,
        )
    finally:
        try:
            await _browser(session, "close", timeout=30)
        except Exception:
            logger.warning("Could not close YouTube deletion session %s", session)
    entry.update({"status": "deleted", "deleted_at": datetime.now(timezone.utc).isoformat()})
    return _record(task, "youtube", entry)["platforms"]["youtube"]


def prepare_apple_podcast(task: TaskResponse) -> dict[str, Any]:
    """Create a valid episode feed; Podcasts Connect submission is deferred."""
    if not task.audio_path or not Path(task.audio_path).is_file():
        raise FileNotFoundError("Narration audio is missing")
    podcast_dir = config.OUTPUTS_DIR / "podcast"
    podcast_dir.mkdir(parents=True, exist_ok=True)
    episodes_path = podcast_dir / "episodes.json"
    try:
        episodes = json.loads(episodes_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        episodes = []
    if not isinstance(episodes, list):
        episodes = []
    audio = Path(task.audio_path)
    relative_audio = audio.resolve().relative_to(config.OUTPUTS_DIR.resolve()).as_posix()
    episode = {
        "guid": task.id,
        "title": _title(task),
        "published_at": datetime.now(timezone.utc).isoformat(),
        "duration": int(task.duration_seconds or 0),
        "audio_url": f"/outputs/{relative_audio}",
        "audio_bytes": audio.stat().st_size,
        "summary": _description(task),
    }
    episodes = [episode, *[item for item in episodes if item.get("guid") != task.id]][:100]
    episodes_path.write_text(json.dumps(episodes, indent=2, ensure_ascii=False), encoding="utf-8")

    rss = ET.Element("rss", {"version": "2.0", "xmlns:itunes": "http://www.itunes.com/dtds/podcast-1.0.dtd"})
    channel = ET.SubElement(rss, "channel")
    ET.SubElement(channel, "title").text = "Frontier Tech Daily"
    ET.SubElement(channel, "description").text = "A daily, source-linked frontier technology briefing."
    ET.SubElement(channel, "language").text = "en"
    ET.SubElement(channel, "link").text = "http://localhost:8101/"
    ET.SubElement(channel, "itunes:author").text = "FrontierTechSN"
    for item in episodes:
        node = ET.SubElement(channel, "item")
        ET.SubElement(node, "title").text = item["title"]
        ET.SubElement(node, "guid", {"isPermaLink": "false"}).text = item["guid"]
        published = datetime.fromisoformat(item["published_at"])
        ET.SubElement(node, "pubDate").text = format_datetime(published)
        ET.SubElement(node, "description").text = item["summary"]
        ET.SubElement(node, "itunes:duration").text = str(item["duration"])
        ET.SubElement(node, "enclosure", {
            "url": item["audio_url"], "length": str(item["audio_bytes"]), "type": "audio/wav",
        })
    ET.ElementTree(rss).write(podcast_dir / "feed.xml", encoding="utf-8", xml_declaration=True)
    payload = {
        "status": "feed_ready",
        "prepared_at": datetime.now(timezone.utc).isoformat(),
        "identity": None,
        "url": "/outputs/podcast/feed.xml",
        "external_submission": "deferred_until_podcasts_connect_account_and_public_https_url",
    }
    return _record(task, "apple_podcast", payload)["platforms"]["apple_podcast"]


async def publish_task(
    task: TaskResponse,
    *,
    targets: list[str],
    test_mode: bool,
    visibility: str,
) -> dict[str, Any]:
    if task.status.value != "complete":
        raise ValueError("Only complete tasks can be published")
    for target in dict.fromkeys(targets):
        if target == "youtube":
            await publish_youtube(task, visibility=visibility, test_mode=test_mode)
        elif target == "x":
            await publish_x(task, test_mode=test_mode)
        elif target == "apple_podcast":
            prepare_apple_podcast(task)
        else:
            raise ValueError(f"Unsupported publication target: {target}")
    return read_publication_manifest(task)


async def delete_test_publications(task: TaskResponse, *, targets: list[str]) -> dict[str, Any]:
    for target in dict.fromkeys(targets):
        if target == "youtube":
            await delete_youtube(task)
        elif target == "x":
            await delete_x(task)
        elif target == "apple_podcast":
            continue
    return read_publication_manifest(task)


async def run_auto_publish_pipeline(task: TaskResponse) -> PublicationResult:
    """Dispatch scheduled daily editions only when their task opted in."""
    if task.origin_type == "daily_news":
        if not task.config.auto_publish:
            return PublicationResult("awaiting_review", "Daily automatic publication is disabled")
        try:
            manifest = await publish_task(
                task,
                targets=task.config.publish_targets,
                test_mode=task.config.publish_test_mode,
                visibility=task.config.publish_visibility,
            )
        except Exception as exc:
            return PublicationResult("failed", f"Daily automatic publication failed: {exc}")
        urls = [str(item.get("url")) for item in manifest.get("platforms", {}).values() if item.get("url")]
        return PublicationResult("published", "Daily publication completed", urls[0] if urls else None)

    if task.origin_type != "content_plan" or not task.origin_id:
        return PublicationResult("not_applicable", "Task did not originate from a publishing workflow")
    item = await database.get_content_plan_item(task.origin_id)
    if item is None:
        return PublicationResult("blocked", "Originating plan no longer exists")
    if not config.VIDEO_AUTO_PUBLISH_ENABLED:
        return PublicationResult("awaiting_review", "Global automatic publication is disabled")
    if not item.auto_publish_requested:
        return PublicationResult("awaiting_review", "This content plan requires manual publication")
    return PublicationResult(
        "awaiting_review",
        f"No automatic publisher is configured for {item.platform}",
    )
